version: 2
jobs:
  build:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs12
    working_directory: ~/covid-api
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            pip install -e .["deploy"] --user
            npm install -g cdk

      - run:
          name: create lambda package
          command: |
            docker build . -t lambda:latest -f Dockerfiles/lambda/Dockerfile
            docker run --rm -v $PWD:/local/ lambda:latest /bin/sh -c 'cp /tmp/package.zip /local/package.zip'
            ls
      - deploy:
          name: master branch deployed to cdk stack
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              STAGE='prod' cdk deploy covid-api-lambda-prod --region us-east-1
            fi
