version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    environment:
      - TOXENV: py37
    working_directory: ~/covid-api
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install tox codecov pre-commit --user
      - run:
          name: copy config.yml
          command: cp stack/config.yml.example stack/config.yml
      - run:
          name: test
          command: ~/.local/bin/tox
      - run:
          name: run pre-commit
          command: ~/.local/bin/pre-commit run --all-files

  deploy-staging:
    machine: 
      image: ubuntu-2004:202010-01
    working_directory: ~/covid-api
    steps:
      - checkout
      - run: 
          name: use python 3
          command: |
            pyenv global 3.8.5

      - run:
          name: install dependencies
          command: |
            pip install -e .["deploy"] --user
            npm install -g cdk

      - deploy:
          name: develop branch deployed to staging cdk stack            
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              STAGE='staging' cdk deploy ${PREFIX}-dataset-metadata-generator-staging --region ${AWS_REGION} --require-approval never  
              STAGE='staging' VPC_ID='${VPC_ID}' cdk deploy ${PREFIX}-lambda-staging --region ${AWS_REGION} --require-approval never
            fi

  deploy-production:
    machine: 
      image: ubuntu-2004:202010-01
    working_directory: ~/covid-api
    steps:
      - checkout
      - run: 
          name: use python 3
          command: |
            pyenv global 3.8.5

      - run:
          name: install dependencies
          command: |
            pip install -e .["deploy"] --user
            npm install -g cdk

      - deploy:
          name: master branch deployed to production cdk stack
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              STAGE='prod' cdk deploy ${PREFIX}-dataset-metadata-generator-prod --region ${AWS_REGION} --require-approval never  
              STAGE='prod' cdk deploy ${PREFIX}-lambda-prod --region ${AWS_REGION} --require-approval never
            fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy-staging: 
          requires:
            - test
          filters:
            branches:
              # only: /^feature\/.*/
              only: develop
      - deploy-production:
          requires:
            - test
          filters:
            branches:
              only: master